### ISSUE TITLE
In-app chat push notification issues

### ISSUE THREAD

**Issue by smaradona** [Instabug/android-sample#89]
Hey there! Not sure if this is the right place to ask, but I'm having issues configuring push notifications for the in-app chat on Android (I successfully configured this on iOS).

This is what I've tried, following this docs: https://docs.instabug.com/docs/android-in-app-chat

- Saved GCM API_KEY on Instabug's dashboard
- Added this line to my code: `Instabug.setPushNotificationRegistrationToken(token);`
- Added the code to check if the received notification is an Instabug notification.

I'm trying with a couple of Android phones and even though the `setPushNotificationRegistrationToken` line with the correct push token for that device is called, when I reply a chat message from Instabug's dashboard, the push notification never arrives, so I'm wondering if the registration push token gets sent to Instabug at all.

Looking at the Push Notification tab on Instabug dashboard, I see a different way to send the push token: `Instabug.setGcmRegistrationToken(token);`. I'm using SDK v3.4.0, but when I try to build the app using this way, I get an error:

`error: cannot find symbol` 
`symbol:   method setGcmRegistrationToken(String)`

Is it because I'm using v3.4.0? It says it should work with v2.4.0 or above.

Any help would be appreciated. Thanks a lot!

**Comment by Korazy** [comment]
Hey @smaradona, 

Sorry for the late response, let me check this and get back to you ASAP.

**Comment by Korazy** [comment]
@smaradona can you please upgrade to the latest version and give it another go?

**Comment by ghataa** [comment]
Ok, solved! I used wrong (legacy) Firebase API key. Details:
![not_this](https://user-images.githubusercontent.com/26881582/46004865-3d4e7b80-c0b4-11e8-9506-2577c4a54694.jpg)
![but_this](https://user-images.githubusercontent.com/26881582/46004870-40e20280-c0b4-11e8-896f-ec5498a96629.jpg)
